name: Private EC2 via SSM and ECR

on:
    push:
        branches: [ "main" ]

jobs:
    build-and-deploy:
        name: Build and Deploy to EC2(with SSM and ECR)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # SSM / ECR credentials configuration(AWS 자격 증명)
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: "${{ secrets.AWS_REGION }}"

            - name: Login to Amazon ECR
              id: login-ecr     # ECR Registry에 로그인하여 Docker 이미지를 푸시할 수 있도록 설정
              uses: aws-actions/amazon-ecr-login@v2

            # Build and Push Docker Image to ECR: 사용자 계정에 역할 필요
            - name: Build and Push Docker Image to ECR
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
                IMAGE_TAG: ${{ secrets.IMAGE_TAG}}
              run: |
                # Build the Docker image
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                # Push the Docker image to ECR
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            - name: Deploy to EC2 via SSM
              run: |
                # SSM을 사용하여 EC2 인스턴스에 명령 실행
                IMAGE_URL="${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ secrets.IMAGE_TAG}}"

                aws ssm send-command \
                  --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
                  --document-name "AWS-RunShellScript" \
                  --parameters 'commands=[
                    "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
                    "sudo docker pull 458894893383.dkr.ecr.ap-south-1.amazonaws.com/std5/ecr:ex7-v2",
                    "sudo docker stop nginx-container || true",
                    "sudo docker rm nginx-container || true",
                    "sudo docker run -d --name nginx-container -p 80:80 458894893383.dkr.ecr.ap-south-1.amazonaws.com/std5/ecr:ex7-v2"
                  ]' \
                --region ${{ secrets.AWS_REGION }}
